import { LogEntry, AppSettings } from '../types';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';
import { format, isValid } from 'date-fns';

export function saveLogs(logs: LogEntry[]) {
  localStorage.setItem('pat_logs', JSON.stringify(logs));
}

export function loadLogs(): LogEntry[] {
  const stored = localStorage.getItem('pat_logs');
  return stored ? JSON.parse(stored) : [];
}

export function saveSettings(settings: AppSettings) {
  localStorage.setItem('pat_settings', JSON.stringify(settings));
}

export function loadSettings(): AppSettings {
  const stored = localStorage.getItem('pat_settings');
  return stored ? JSON.parse(stored) : {
    companyName: '',
    testerLicense: '',
    contactNumber: ''
  };
}

function safeFormatDate(dateString: string | undefined, formatStr: string): string {
  if (!dateString) return 'N/A';
  const date = new Date(dateString);
  return isValid(date) ? format(date, formatStr) : 'Invalid Date';
}

export function exportToCSV(logs: LogEntry[]) {
  const headers = ['ID', 'Timestamp', 'Appliance ID', 'Description', 'Status', 'Frequency (Months)', 'Next Test Due', 'Notes', 'Image URL'];
  const rows = logs.map(log => [
    log.id,
    log.timestamp,
    log.applianceId,
    `"${log.description.replace(/"/g, '""')}"`, // Escape quotes
    log.status,
    log.testFrequency || 'N/A',
    safeFormatDate(log.nextTestDate, 'yyyy-MM-dd'),
    `"${(log.notes || '').replace(/"/g, '""')}"`,
    log.imageUrl || ''
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `pat_logs_${safeFormatDate(new Date().toISOString(), 'yyyy-MM-dd')}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToPDF(logs: LogEntry[], settings: AppSettings, title: string = "PAT Testing Report") {
  const doc = new jsPDF();
  const total = logs.length;
  const passed = logs.filter(l => l.status === 'Pass').length;
  const failed = logs.filter(l => l.status === 'Fail').length;
  const passRate = total > 0 ? (passed / total) * 100 : 0;

  // --- Header Section ---
  doc.setFillColor(37, 99, 235); // Blue header bg
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text(title, 14, 18);
  
  doc.setFontSize(10);
  doc.text(`Report Date: ${format(new Date(), 'PPP')}`, 14, 28);
  doc.text(`Generated by: ${settings.companyName}`, 14, 33);

  // --- Company Details Box ---
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(10);
  doc.text(`Tester: ${settings.testerLicense}`, 14, 50);
  doc.text(`Contact: ${settings.contactNumber}`, 14, 55);

  // --- Summary Statistics (Graphical) ---
  const summaryY = 45;
  const summaryX = 120;
  
  // Summary Box
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(250, 250, 250);
  doc.roundedRect(summaryX, summaryY, 75, 35, 3, 3, 'FD');

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text("Summary", summaryX + 5, summaryY + 8);

  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Total Items: ${total}`, summaryX + 5, summaryY + 16);
  
  doc.setTextColor(0, 150, 0);
  doc.text(`Passed: ${passed}`, summaryX + 5, summaryY + 22);
  
  doc.setTextColor(200, 0, 0);
  doc.text(`Failed: ${failed}`, summaryX + 35, summaryY + 22);

  // Visual Pass Rate Bar
  doc.setDrawColor(230, 230, 230);
  doc.setFillColor(230, 230, 230);
  doc.rect(summaryX + 5, summaryY + 26, 65, 4, 'F'); // Background bar

  if (total > 0) {
    doc.setFillColor(34, 197, 94); // Green
    doc.rect(summaryX + 5, summaryY + 26, 65 * (passed / total), 4, 'F'); // Pass portion
  }

  // --- Table ---
  const tableColumn = ["Appliance\nID", "Description", "Status", "Freq", "Next Due", "Notes", "Image"];
  const tableRows = logs.map(log => [
    log.applianceId,
    log.description,
    log.status,
    log.testFrequency ? `${log.testFrequency}m` : 'N/A',
    safeFormatDate(log.nextTestDate, 'yyyy-MM-dd'),
    log.notes || '',
    log.imageUrl || ''
  ]);

  autoTable(doc, {
    startY: 85,
    head: [tableColumn],
    body: tableRows,
    headStyles: { 
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: 'bold',
      valign: 'middle'
    },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    bodyStyles: { 
      minCellHeight: 25, // Approx 3 lines + padding
      valign: 'middle',
      fontSize: 9
    },
    styles: { cellPadding: 3, overflow: 'linebreak' },
    columnStyles: {
      0: { cellWidth: 25, fontStyle: 'bold' }, // ID - Shrunk to make room
      1: { cellWidth: 35 }, // Desc - Shrunk to make room
      2: { cellWidth: 18, fontStyle: 'bold' }, // Status - Increased
      3: { cellWidth: 15, halign: 'center' }, // Freq - Increased
      4: { cellWidth: 25 }, // Next Due
      5: { cellWidth: 'auto' }, // Notes
      6: { cellWidth: 25 } // Image
    },
    didParseCell: function(data) {
      // Color coding for Status
      if (data.section === 'body' && data.column.index === 2) {
        if (data.cell.raw === 'Pass') {
          data.cell.styles.textColor = [22, 163, 74]; // Green-600
        } else {
          data.cell.styles.textColor = [220, 38, 38]; // Red-600
        }
      }
      // Clear text for Image column so base64 doesn't print
      if (data.section === 'body' && data.column.index === 6) {
        data.cell.text = [];
      }
    },
    didDrawCell: function(data) {
      if (data.section === 'body' && data.column.index === 6 && data.cell.raw) {
        const imgData = data.cell.raw as string;
        if (imgData && imgData.startsWith('data:image')) {
          try {
            const padding = 2;
            const size = data.cell.height - (padding * 2);
            // Draw image centered in cell
            doc.addImage(imgData, 'JPEG', data.cell.x + padding, data.cell.y + padding, size, size, undefined, 'FAST');
          } catch (e) {
            console.error('Error adding image to PDF', e);
          }
        }
      }
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    doc.text(`Generated by PAT Logger App`, 14, 290);
  }

  doc.save(`pat_report_${safeFormatDate(new Date().toISOString(), 'yyyy-MM-dd')}.pdf`);
}
